### ISSUE TITLE
Insert the first step guide

### ISSUE THREAD

**Issue by bmen** [ASKnet-Open-Training/Github-Guidance#1]

**Comment by PyGamma** [comment]
This issue is not sufficiently described,  please add more descriptions to this issues to fully communicate what you are meaning so that we can undertake it. Thanks for your response.
I.e what do you mean by first step guide in simple and clear statement.

**Comment by PyGamma** [comment]
I think this task is below our current status as far as git hub is concerned. That is if I understood the  creater right.
Thanks

**Comment by bmen** [comment]
It's done. https://asknet-open-training.github.io/Github-Guidance/pages/github-repo/repository-overview/
