### ISSUE TITLE
Upload images to Repo

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/Github-Guidance#11]
![Adding-images-files-to-Repo](https://user-images.githubusercontent.com/8081055/101546888-bc84ad00-39a9-11eb-979e-1a2985074625.gif)

**Comment by PyGamma** [comment]
Resolved, thanks for the time and service

**Comment by bmen** [comment]
it's done: https://asknet-open-training.github.io/Github-Guidance/pages/github-repo/image-upload/
