### ISSUE TITLE
What factors should be considered when creating a repository? 

### ISSUE THREAD

**Issue by dawaedina27** [ASKnet-Open-Training/Github-Guidance#14]

**Comment by timmwille** [comment]
Hi @dawaedina27 I think it is explained in #2 
check my gif animation here:
https://github.com/ASKnet-Open-Training/Github-Guidance/issues/2#issuecomment-741100053

**Comment by timmwille** [comment]
is there anything else you had in mind with that question?

**Comment by dawaedina27** [comment]
Yeah its explained in the gif animation I didn't open at first

But in the process of finding answer to the issue, I came across this:

Factors to consider when choosing a repository
What functionality do you need now?
- Version-control system, including web interface for online code-browsing
- Mailing lists, list management and archives
- Bug/issue tracker
- Basic web server for project/software pages
- News
- Software package hosting/publishing
- Statistics reporting (e.g. number of commits, number of downloads)
- Forums
- Wikis
- Project/release management
- Access Control (e.g. setting up project level roles)
How easy is it to upgrade to additional functionality in the future?
What is your preferred version-control system, e.g. CVS, SVN, Git, Mercurial?
Is it important to have your code publicly available?
Are all your code committers local?
How easy is it to integrate other things you run separately (e.g. a website) with the
repository?
How good is the support for your IDEs of choice?
Is there support for authentication systems such as OpenID or SSH keys?
What additional forge, social networking, project-management functionality do you
want from the site? e.g. GitHub is good for social coolness
Where are similar projects to yours hosted?
What's the speed of upload/download?
How easy is it to backup the entire repository (code, mailing lists, issue tickets, ...)
How established and stable is the repository?
How good is the user support?
How much effort do you have to put into repository maintenance?
Would it be better to use more than one repository, e.g. code stored in GitHub and
a link to Assembla for its extra tools?
What are the Service Level Agreements for uptime, downtime, time to fix outages
and bandwidth?
If you are trying to migrate your project from one repository to another, you might
also want to consider two extra factors:
How easy will it be to transfer not just your code, but your community, to the new
site, e.g. do you have mailing list archives, wikis, user accounts
Do you need to keep the revision history associated with your code, or can you
start afresh?
