### ISSUE TITLE
How to add/change a Social Preview Picture to a Repository

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/Github-Guidance#15]
![Add-Preview-Picture-forRepo](https://user-images.githubusercontent.com/8081055/102211865-8e84f880-3ed4-11eb-8514-6c59c0d50d84.gif)

**Comment by timmwille** [comment]
Here you can test it is working:
https://socialsharepreview.com

**Comment by bmen** [comment]
done see here: https://asknet-open-training.github.io/Github-Guidance/github-repo#addchange-a-social-preview-picture-to-a-repository
