### ISSUE TITLE
Is it usefull to make use of Commit comment function?

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/Github-Guidance#17]
in what case does it make sense to use the Commit comment functionality?

For example in this case I can see a lot of content that belongs into the repo code and/or wiki but definitely not in a commit comment:
 https://github.com/ASKnet-Open-Training/magnet-light/commit/d5dca34f904fd8862700d0c0c4e6398a37d5a6f9

**Comment by chardso** [comment]
Yeah ,it was so confusing to me as where to write my report from my findings, but I came to realise where to write them after I have already written them as commit comments,next time better.

**Comment by timmwille** [comment]
@bmen can you check?

**Comment by chardso** [comment]
How do I move the commit comments to a single file in the readme?

**Comment by PyGamma** [comment]
Thanks so much for this question, ideally commit comment in most cases are used to identify the commit one makes, it includes the statement to explain the changes you have done to the repository, and is it also the way the repository owner can reply to your  request and notified the changes you are required to make if your code it to be merged in the master branched.
