### ISSUE TITLE
Automated checklist from Github for all important files in a repo

### ISSUE THREAD

**Issue by bmen** [ASKnet-Open-Training/Github-Guidance#19]

**Comment by chardso** [comment]
![FB_IMG_16103038154523090](https://user-images.githubusercontent.com/71114711/104133120-806eae80-5392-11eb-9612-b67ea38be7df.jpg)
Open your repository.scroll to insights.
![FB_IMG_16103038154523090](https://user-images.githubusercontent.com/71114711/104133120-806eae80-5392-11eb-9612-b67ea38be7df.jpg)

**Comment by chardso** [comment]
![FB_IMG_16103038306777294](https://user-images.githubusercontent.com/71114711/104133138-a8f6a880-5392-11eb-8d26-ad8c95108604.jpg)
Click on insights and it brings the page bellow.
![FB_IMG_16103038306777294](https://user-images.githubusercontent.com/71114711/104133138-a8f6a880-5392-11eb-8d26-ad8c95108604.jpg)

**Comment by chardso** [comment]
M
![FB_IMG_16103038433355262](https://user-images.githubusercontent.com/71114711/104133161-d6dbed00-5392-11eb-983c-958c4809a666.jpg)
Click on the community ,it will display checklist.
![FB_IMG_16103038433355262](https://user-images.githubusercontent.com/71114711/104133161-d6dbed00-5392-11eb-983c-958c4809a666.jpg)

**Comment by chardso** [comment]
Check for the field of interest for example if its license add and select the open source license of your choice.
But for the sake of the above one its already marked ,meaning the repository has the license already .
In case it's not there they normally indicate the word add in the small box normally at the right hand side,just click the add in the small box on th right hand side and select the license of your choice.

**Comment by bmen** [comment]
> Click on insights and it brings the page bellow.

Thank you @chardso! I think you need to wait a moment for him to upload the image. Don't click on "comment" too quickly.
You will see a circle at the bottom. It must disappear first and then you can click on the button "comment".

![Bildschirmfoto von 2021-01-10 20-05-25](https://user-images.githubusercontent.com/389294/104132754-a3439780-537f-11eb-846f-6e6a91e449a6.png)

**Comment by chardso** [comment]
No eliminate other screen shorts,network was poor.

**Comment by bmen** [comment]
thank you. I will make a site in the guide about this :)

**Comment by bmen** [comment]
@chardso your manual is in the guide: https://asknet-open-training.github.io/Github-Guidance/pages/github-repo/repo-checkup/

:+1:
