### ISSUE TITLE
Insert the gif of the guide to create a github repository and write a short documentation

### ISSUE THREAD

**Issue by bmen** [ASKnet-Open-Training/Github-Guidance#2]

**Comment by timmwille** [comment]
![New-Repository-with-Readme-Open-License](https://user-images.githubusercontent.com/8081055/101546309-e25d8200-39a8-11eb-8dd2-3729520f4c5f.gif)

**Comment by timmwille** [comment]
make sure to have a short clear name without spaces and initialise with README plus add an Open Source License

**Comment by PyGamma** [comment]
Looks Great for me,
