### ISSUE TITLE
HOW TO DELETE A REPOSITORY WHERE NEED BE?

### ISSUE THREAD

**Issue by gibertgibs** [ASKnet-Open-Training/Github-Guidance#20]
# <How to delete your repository where need be.> 

NOTICE: Well, this tutorial is a directive to help one delete his/her repository where need be. I understand at times, most people create repositories they didn't want to, meaning creating it for fun with a plan of deleting it when the purpose is done. So this tutorial will help guide you to the destination of deleting a repository. 

## Step 1
Just click settings in the repository you want to delete and scroll down.

### Step 2
1. Scroll to the danger area where you will find;
- Changing your repository's status from PRIVATE to PUBLIC.
- DELETING your repository.
2. After clicking on Delete, you will have to confirm whether you are sure to delete the respository or not, And yes, confirm it and it's done.

![Screenshot_20210110-013342](https://user-images.githubusercontent.com/69734297/104263553-dd558c00-549a-11eb-8a5b-fb6daa8975b3.png)

![Screenshot_20210110-013358](https://user-images.githubusercontent.com/69734297/104263327-746e1400-549a-11eb-922b-4eb9afe024aa.png)

NOTICE: Now you can use the whole world of Markdown to create your guide (upload headings, bullet points or images). More informations: https://asknet-open-training.github.io/Github-Guidance/pages/github-markdown

Examples:
### Headline 3 If a step are more complex, can also be used headings level 3
normal text

- Bullet
- List

Drag & Drop or upload an image and insert it anywhere you like.
![FB_IMG_16103038433355262](https://user-images.githubusercontent.com/71114711/104133161-d6dbed00-5392-11eb-983c-958c4809a666.jpg)

**Comment by bmen** [comment]
@gibertgibs your manual is now in the guide: https://asknet-open-training.github.io/Github-Guidance/pages/github-repo/delete-repository/

:+1:

**Comment by bmen** [comment]
@gibertgibs your draft was wonderful! I just needed to copy your content. I only had to make a few small changes. I documented them in the screenshot.

![Selection_081](https://user-images.githubusercontent.com/389294/104309040-d302b480-54d1-11eb-97af-44d0b7fba62a.png)

**Comment by gibertgibs** [comment]
Okay....Thanks alot
