### ISSUE TITLE
How to go to your Profile to share with others how to find you

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/Github-Guidance#5]
![Go-To-Your-Profile](https://user-images.githubusercontent.com/8081055/101483677-cf22c600-3958-11eb-86eb-303ce9c7144f.gif)

**Comment by timmwille** [comment]
Copy and share that Profile URL
![Profile-URL](https://user-images.githubusercontent.com/8081055/101484255-9fc08900-3959-11eb-9c60-136e40f2022a.gif)

**Comment by bmen** [comment]
Guide is created: https://github.com/ASKnet-Open-Training/Github-Guidance/wiki/github-account#how-to-go-to-your-profile-to-share-with-others-how-to-find-you
